### ISSUE TITLE
MAP enlloc de MAN

### ISSUE THREAD

**Issue by xavigiro** [gdsa-upc/What-a-building-App#3]
He vist a la vostra [https://github.com/gdsa-upc/What-a-building-App/blob/gh-pages/Notebooks/S6_Rank_resultats.ipynb notebook] que obteniu un MAP de 0.22. És bona aquesta dada ? 

També he vist però que n'hi heu dit MAN enlloc de MAP. Ho corregiu ? També seria bo que eliminéssiu del notebook tantes xifres. Amb el valor final ja n'hi hauria prou.

**Comment by sergisantana** [comment]
Hola! Gràcies. Canviarem el notebook i el Man average precision (MAP) dels scripts. El resultat es real, si agafem 50 imatges vem aconseguir un 0,33, amb les 450 de training hem aconseguit un 0,22.

**Comment by sergisantana** [comment]
Perdó, Mean Average Precision.
